services:
  - type: web
    name: innovatex-ide
    env: docker
    envVars:
      - key: PORT
        value: 8080
      - key: PASSWORD
        value: ""
    disk:
      name: innovatex-data
      mountPath: /root/.local/share/innovatex-ide
      sizeGB: 1
