{{- if or .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "innovatex-ide.labels" . | nindent 4 }}
  name: {{ template "innovatex-ide.serviceAccountName" . }}
{{- end -}}
